### PR TITLE
New solver for slotted-type advection problems

### PR DESCRIPTION
**Pull request by taataam**
This commit fixes issue #32 by adding a new advection solver. It considers the velocity field as nonuniform (constant) which allows to simulate problems such as Zalesk slotted disk. A new slotted problem is added other than the tophat and smooth ones.

### CODE REVIEW

**Comment by taataam** [comment]
I've updated my fork to resolve the conflict and they shouldn't be have any issue, I don't know why it still complains about the conflicts.

**Comment by harpolea** [comment]
@taataam, could you fix the merge conflicts and make sure the tests pass before we close this pull request? (I tried to do this on github but broke the tests, so it might be easier if you do it on your fork) Otherwise the code looks great!

**Comment by harpolea** [comment]
Also, it would be great if you could add the advection_uniform problem to solver_test.ipynb

**Comment by taataam** [comment]
@harpolea  I've made the requested changes and the conflicts are resolved.

**Comment by harpolea** [comment]
@taataam Great thanks! I'll merge this now

**Pull request merged**
