### PR TITLE
RIP fortran

### PR DESCRIPTION
**Pull request by harpolea**
This removes all the Fortran in the code, makes the signatures to some functions a bit more pythonic and updates the benchmarks (which were also failing for the fortran).

### CODE REVIEW

**Comment by IanHawke** [comment]
Concerned that Github doesn't have a crying emoji.

**Comment by zingale** [comment]
do we even need `mk.sh` anymore?

**Comment by harpolea** [comment]
Not for building, but `mk.sh clean` can be useful to remove the cached compiled code as Numba doesn't delete it automatically and you can end up with quite a few files in `__pycache__` if you change the code a lot. I expect most users won't be changing any of the numba-compiled code, so it probably won't be a problem for them. Alternatively, I could just get rid of the `cache=True` option - this would add 2-5 seconds of start up time at the start of every run, and I basically only put it there because I'm impatient.

**Comment by zingale** [comment]
I get large-ish errors for the lm_atm bubble:

pyro ...
initializing the bubble problem...
comparing to: lm_atm/tests/lm_bubble_128_0065 
 
variable comparisons:
density              error =        0.01497213509
x-velocity           error =      0.0005998435495
y-velocity           error =      0.0004395507152
eint                 error =        0.03760221844
phi-MAC              error =      9.470132485e-07
phi                  error =      2.655483131e-05
gradp_x              error =       0.002500767966
gradp_y              error =       0.002386601402
ERROR: one or more variables don't agree

need to double check the Fortran

**Comment by zingale** [comment]
okay, so I agree perfectly (numba and Fortran) if I use the stored output on `master` in `lm_atm/tests/` as the comparison.  But I don't agree if I compare against the stored output on `numba` in `lm_atm/tests/`.  Since the numba and Fortran agree perfectly, my guess is that the benchmark on the `numba` branch is wrong?

**Comment by harpolea** [comment]
That's weird - I recomputed the benchmarks as I was getting the same small errors for both the numba and Fortran versions. I'll try running again and see if I see the same thing

**Comment by harpolea** [comment]
I see the reverse of you: I get the same exact error if I use the version in `master`, but get no errors if I use the version in `numba`.

**Comment by harpolea** [comment]
The benchmarks varied depending on which machine/version of the compiler was used (especially for the problems which used the multigrid solver). I think the ones on this branch were compiled on xrb, but should probably be compiled on groot/bender instead

**Comment by zingale** [comment]
okay... I'll regenerate them on groot tomorrow.  Can you resolve those conflicts?

also, I assume it is convention that numba files start with `__` (like `__interface.py`)?

**Comment by harpolea** [comment]
Sure, I'll have a look at this tomorrow

**Comment by zingale** [comment]
the conflicts were my fault.  Not sure what I did.

I'll regenerate the benchmarks tomorrow and then merge.

**Comment by zingale** [comment]
I've reset the benchmarks to the `master` branch and the results agree to roundoff levels.  I've also confirmed that the 4th order compressible still converges as 4th order.

**Pull request merged**
